### ISSUE TITLE
Java DSL 

### ISSUE THREAD

**Issue by db-mitchell** [spring-cloud-stream-app-starters/httpclient#12]
1. - I borrowed the code from https://github.com/spring-cloud/spring-cloud-dataflow-samples
2. - and tweaked the code to build definition style time | log.
3. - I have dataflow sever running on openstack VM I used to the docker compose method to install which has the kafka as the message bus.
4. - That has all the apps imported including time src and log sink.
5. - There for I have commented out the import applications method.

The stream is deployed successfully, however when I tail the log it says:

[cloud-user@deepali-elasticml-metro-hello bin]$ docker exec -it dataflow-server tail -f /tmp/spring-cloud-deployer-3464565830375206786/woodchuck-1532636252014/woodchuck.log/stdout_0.log
2018-07-26 20:19:02.557  INFO 18999 --- [me.woodchuck-15] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [localhost:5672]
2018-07-26 20:19:07.559  WARN 18999 --- [me.woodchuck-15] o.s.a.r.l.SimpleMessageListenerContainer : Consumer raised exception, processing can restart if the connection factory supports it. Exception summary: org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused (Connection refused)
2018-07-26 20:19:07.560  INFO 18999 --- [me.woodchuck-15] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@6b0f1b9a: tags=[{}], channel=null, acknowledgeMode=AUTO local queue size=0
2018-07-26 20:19:07.561  INFO 18999 --- [me.woodchuck-16] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [localhost:5672]
2018-07-26 20:19:12.563  WARN 18999 --- [me.woodchuck-16] o.s.a.r.l.SimpleMessageListenerContainer : Consumer raised exception, processing can restart if the connection factory supports it. Exception summary: org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused (Connection refused)
2018-com/spring-cloud/spring-cloud-dataflow-samples

Here is the java code that I am using.

**Comment by db-mitchell** [comment]
I forgot to attach the src code.package com.example.scdfdsl;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.dataflow.core.ApplicationType;
import org.springframework.cloud.dataflow.rest.client.DataFlowOperations;
import org.springframework.cloud.dataflow.rest.client.DataFlowTemplate;
import org.springframework.cloud.dataflow.rest.client.dsl.DeploymentPropertiesBuilder;
import org.springframework.cloud.dataflow.rest.client.dsl.Stream;
import org.springframework.cloud.dataflow.rest.client.dsl.StreamApplication;
import org.springframework.cloud.dataflow.rest.client.dsl.StreamBuilder;
import org.springframework.context.annotation.Bean;

import java.net.URI;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SpringBootApplication
public class ScdfdslApplication implements ApplicationRunner {

	public static void main(String[] args) {
		SpringApplication.run(ScdfdslApplication.class, args);
	}

	private final Logger logger = LoggerFactory.getLogger(ScdfdslApplication.class);

	@Autowired
	private StreamApplication source;

	@Autowired
	private StreamApplication processor;

	@Autowired
	private StreamApplication sink;

	@Autowired
	private DataFlowOperations dataFlowOperations;

	@Autowired
	private StreamBuilder builder;

	// Using @Bean defintions makes it easier to reuse an application in multiple streams
	@Bean
	public StreamApplication source() {
		return new StreamApplication("http").addProperty("server.port", 9900);
	}

	@Bean
	public StreamApplication processor() {
		return new StreamApplication("splitter")
				.addProperty("producer.partitionKeyExpression", "payload");
	}

	@Bean
	public StreamApplication sink() {
		return new StreamApplication("log")
				.addDeploymentProperty("count", 2);
	}

	@Override
	public void run(ApplicationArguments applicationArguments) throws Exception {
		//importApplications();
		if (applicationArguments.containsOption("style")) {
			String style = applicationArguments.getOptionValues("style").get(0);
			if (style.equalsIgnoreCase("definition")) {
				// DEFINITION STYLE
				definitionStyle(dataFlowOperations);
			} else if (style.equalsIgnoreCase("fluent")) {
				// FLUENT STYLE
				fluentStyle(dataFlowOperations);
			} else {
				logger.info("Style [" + style + "] not supported");
			}
		} else {
			definitionStyle(dataFlowOperations);
		}
	}


	private void definitionStyle(DataFlowOperations dataFlowOperations) throws InterruptedException {
		Map<String, String> deploymentProperties = createDeploymentProperties();

		logger.info("Deploying stream.");
/*
		Stream woodchuck = builder
				.name("woodchuck")
				.definition(
				"http --server.port=9900 | splitter --expression=payload.split(' ') | log")
				.create()
				.deploy(deploymentProperties);
		
	*/	
//		Stream woodchuck = builder
//				.name("woodchuck")
//				.definition(
//				"rabbit --password=dataflow --queues=springdataflow-q --host=172.24.172.184 --virtual-host=springdataflow --username=springdataflow | splitter --expression=payload.split(' ') | log")
//				.create()
//				.deploy(deploymentProperties);
		
		Stream woodchuck = builder
				.name("woodchuck")
				.definition(
				"time | log")
				.create()
				.deploy(deploymentProperties);

		waitAndDestroy(woodchuck);
	}

	private void importApplications() {
		this.dataFlowOperations.appRegistryOperations().register("log", ApplicationType.sink,
				"maven://org.springframework.cloud.stream.app:log-sink-rabbit:1.3.1.RELEASE",
				"maven://org.springframework.cloud.stream.app:log-sink-rabbit:jar:metadata:1.3.1.RELEASE",
				true);
		this.dataFlowOperations.appRegistryOperations().register("splitter", ApplicationType.processor,
				"maven://org.springframework.cloud.stream.app:splitter-processor-rabbit:1.3.1.RELEASE",
				"maven://org.springframework.cloud.stream.app:splitter-processor-rabbit:jar:metadata:1.3.1.RELEASE",
				true);
//		this.dataFlowOperations.appRegistryOperations().register("http", ApplicationType.source,
//				"maven://org.springframework.cloud.stream.app:http-source-rabbit:1.3.1.RELEASE",
//				"maven://org.springframework.cloud.stream.app:http-source-rabbit:jar:metadata:1.3.1.RELEASE",
//				true);
		
		this.dataFlowOperations.appRegistryOperations().register("rabbit", ApplicationType.source,
				"maven://org.springframework.cloud.stream.app:rabbit-source-kafka-10:1.3.1.RELEASE",
				"maven://org.springframework.cloud.stream.app:rabbit-source-rabbit:jar:metadata:1.3.1.RELEASE",
				true);
		
		this.dataFlowOperations.appRegistryOperations().register("time", ApplicationType.source,
				"maven://org.springframework.cloud.stream.app:time-source-kafka-10:1.3.1.RELEASE",
				"maven://org.springframework.cloud.stream.app:time-source-rabbit:jar:metadata:1.3.1.RELEASE",
				true);
		
		
	}

	private void fluentStyle(DataFlowOperations dataFlowOperations) throws InterruptedException {

		logger.info("Deploying stream.");

		Stream woodchuck = builder
				.name("woodchuck")
				.source(source)
				.processor(processor)
				.sink(sink)
				.create()
				.deploy();

		waitAndDestroy(woodchuck);
	}

	private Map<String, String> createDeploymentProperties() {
		DeploymentPropertiesBuilder propertiesBuilder = new DeploymentPropertiesBuilder();
		propertiesBuilder.memory("log", 512);
		propertiesBuilder.count("log",2);
		propertiesBuilder.put("app.splitter.producer.partitionKeyExpression", "payload");
		return propertiesBuilder.build();
	}


	private void waitAndDestroy(Stream stream) throws InterruptedException {
		while(!stream.getStatus().equals("deployed")){
			logger.info("Wating for deployment of stream.");
			Thread.sleep(5000);
		}

		logger.info("Letting the stream run for 2 minutes.");
		// Let woodchuck run for 2 minutes
		Thread.sleep(240000);

		logger.info("Destroying stream");
		stream.destroy();
	}

}

**Comment by db-mitchell** [comment]
It seems when creating and deploying streams via Java DSL, it is assuming that rabbit message bus is running locally, at least that is what I am seeing on the logs. ?

**Comment by sabbyanandan** [comment]
Hi, @db-mitchell. First of all, this report has nothing to do with `httpclient` processor. Before I close it, though, I wanted to mention a few things.

The App that uses Java DSL is yet another client similar to the SCDF Shell or Dashboard. You refer to OpenStack, but we don't provide anything directly to support that platform. If your goal is to deploy to OpenStack, you either have to use PCF or K8S implementation of SCDF. And of course, the expectation is that you'd have the necessary messaging middleware ready and available for to use at runtime because the Apps would use it for communication. You can refer to [SCDF CloudFoundry Acceptance Tests](https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/tree/dc4bbd8a8437864812de40da1cb70cbc14f60b5c/cloudfoundry) for more info. 

Lastly, for questions like this, please use StackOverflow or Gitter going forward.
