### ISSUE TITLE
controlling retry maxAttempts

### ISSUE THREAD

**Issue by rajurc** [spring-cloud-stream-app-starters/httpclient#34]
Hi 
I am testing httpclient-processor-kafka spring cloud app with both success and error cases in a Spring cloud dataflow server.

For successful processing scenario, the HTTP request is being retried attempted for 3 times which is the default maxAttempts for this app for calling http request.

How the retrial attempts can be controlled to just one time

**Comment by sobychacko** [comment]
Hi @rajurc This project has been moved to another repository: https://github.com/spring-cloud/stream-applications

`httpclient` app is now refactored into [http request processor](https://github.com/spring-cloud/stream-applications/tree/main/functions/function/http-request-function) function. Please engage with us at the new repository. To answer your question, you can control `maxAttempts` using the property - `spring.cloud.stream.bindings.input.consumer.maxAttempts`. See more details [here](https://docs.spring.io/spring-cloud-stream/docs/3.1.5/reference/html/spring-cloud-stream.html#_retry_template).
